### ISSUE TITLE
Feature request - use floats for base-call quality averages for jsa.np.filter params

### ISSUE THREAD

**Issue by ghost** [mdcao/japsa#14]
Hi again,

Integers are used for Phred base-call quality values for individual bases because they can easily be ASCII-encoded. However, when average values are taken over a read for base-call qualities, the use of floats has advantages, given the coarseness of the Phred scale. Currently, the '--qualMin' and '--qualMax' params of jsa.np.filter (which by definition concern average base-call quals) accept integer values, but the use of floats for these params and the related filtering calculations would allow e.g. for the creation of finer-grained error-profiles for a read dataset.

Thanks for your consideration of this request!

**Comment by hsnguyen** [comment]
Just fixed it and made a push. If you pull the newest version of japsa and run a test with it, that'd be great!
About to make a release soon on July and will update the documentation.
Thank you very much for the feedback!

**Comment by ghost** [comment]
Thanks!

I’ve pulled the latest changes and am running my updated analyses overnight.

I’ll get back to you tomorrow with the results and some background information that you may find interesting.

Best wishes,

Robert

P.S. Completely understand and agree with your explanation about the np.reader issue.

**Comment by ghost** [comment]
Your changes worked really well, thanks again!
