### ISSUE TITLE
npreader

### ISSUE THREAD

**Issue by lmichielsen** [mdcao/japsa#15]
Hi!

I want to run npreader on 1Dsquared reads. Do you know if that's also possible? 
When I look at the scripts it looks like only the 2D, template and complement are used, but I think 1Dsquared will be stored under a different name in the FAST5 file.

Looking forward to your answer, thanks!

**Comment by mbhall88** [comment]
Do you have a sample `fast5` file you can send through so we can test and fix?

**Comment by lmichielsen** [comment]
Hmm it seems nanopore has made it quite complicated. First the reads are all 1D basecalled and a FAST5 is made. When the basecalling is finished, there is the possibility to run another script which looks which reads are 1Dsquared and writes the results immediately to a FASTQ file. So I guess it isn't possible to run npreader on this.

**Comment by mbhall88** [comment]
Without sample data we are unable to test if we can get it working. Are you able to point us in the direction of some 1D-squared data we can test on? I can't seem to find any.

**Comment by mdcao** [comment]
no answer
