### ISSUE TITLE
Formula for estimating changes in repeat units

### ISSUE THREAD

**Issue by a113n** [mdcao/japsa#2]
I am trying to understand your code as part of my personal learning exercise, and I noticed that the formula for estimating changes in repeat units is different from what you wrote in Nucl. Acids Res. (2014) 42 (3): e16. Could you please enlighten me on the rationale of such changes?

In line 632 of japsa/src/main/java/japsa/bio/tr/Fragment2TRV.java, you wrote:

``` java
double eMean = ((meanP / varP) - (counts[i] * trv.getPeriod() * (mean - gMean) / gVar)) * eVar;
```

Whereas the original formula was commented out in line 388:

``` java
//double eMean = ((meanP / varP) - (counts[i] * (mean - gMean) / gVar)) * eVar;
```

Looking forward to your reply soon, thanks!

**Comment by mdcao** [comment]
The previous version (now commented out) worked with number of bases, while the current version works with number of repeat copies.
Hope that makes sense.
Cheers
-M

**Comment by a113n** [comment]
Thanks for your reply earlier! 

Do you actually mean the reverse, where the commented out version worked with the change in number of repeat copies (i.e. the most likely value about Δ), and the current version works with the change in repeat length in nucleotides (i.e. uΔ)? 

However in line 130 of  japsa/src/main/java/japsa/bio/tr/TRV2VCF.java, it looks like you are multiplying the value again with period to get the change in repeat length. Isn't that unnecessary if trv.var is already representing uΔ? Or Is it?

``` java
int nuc = (int) Math.round(trv.var * period);
```
