### ISSUE TITLE
problem with A dynamic, reusable donut chart for D3.js v4

### ISSUE THREAD

**Issue by Infernus92** [mdcao/japsa#20]
i followed your steps, but my donut chart is still static, how to make that dynamic? where can i find the new species.tsv through which the data is being changed? please help

**Comment by mbhall88** [comment]
Hi @Infernus92 ,

This is not an issue with japsa so I am closing this issue. The D3 bl.ocks are linked to my gists. Specifically I think the one you are referring to is [this one](https://gist.github.com/mbhall88/22f91dc6c9509b709defde9dc29c63f2).
I will be happy to help you further though. Probably the easiest thing to do would be for you to make a [JSFiddle](https://jsfiddle.net/) with the code you are trying to use and then email me (mbhall88@gmail.com) the link to it and the issues you are running into and then I can try and debug with you .

**Comment by Infernus92** [comment]
Thank you so much.
The problem got resolved
:)

**Comment by Infernus92** [comment]
Can you tell me how to show sub categories for a species in the same arc
when i hover the mouse to it?
i have shared JSfiddle link with you.

https://jsfiddle.net/150ksv00/

it will be really helpful if you do so.

**Comment by mbhall88** [comment]
I would say you want to use something like [this](https://bl.ocks.org/mbostock/4063423).
I haven't done the partitioning before so I can't really help sorry.
