### ISSUE TITLE
option illen doesn't work in capsim

### ISSUE THREAD

**Issue by alartin** [mdcao/japsa#23]
In capsim, option illen doesn't work and I go through the code and find it is not used at anywhere except option parsing. It should be used somewhere in simulation to setup the read length of illumina read length.

**Comment by c-zhou** [comment]
Hi alartin, thanks very much for your enquiries. The 'illen' parameter should work now. The default is still 250. The maximum is set to 300, which means if you put values greater than 300, it will automatically choose 300. We haven't made a release for this yet, so if you want to try this you need to clone the repository - sorry for that.

**Comment by alartin** [comment]
@c-zhou Many thanks for your quick response! I will try it soon.
