### ISSUE TITLE
Duplicated reads id issue

### ISSUE THREAD

**Issue by alartin** [mdcao/japsa#24]
Hi,
There is potential issue in SimulateCaptureCmd.java. The read name/id might be duplicated. It is easy to fix by appending the numGen variable at the end of the name like this:
`seq.setName(ID + "_" + chrList.get(chrIndex).getName() + "_" + (chrPos + 1) + "_" +(chrPos + fragLength) + "_" + Long.toString(numGen));`

**Comment by mdcao** [comment]
great suggestions. I add in the fragment number
