### ISSUE TITLE
Refactor `consensusSequence()`

### ISSUE THREAD

**Issue by allenday** [mdcao/japsa#25]
https://github.com/mdcao/japsa/blob/0f210c829c258696e40ade0d7c8c94238e6f203c/src/main/java/japsa/bio/np/ErrorCorrection.java#L101

Please refactor this method, we need step 4 available in isolation.

It's a good idea while refactoring to isolate all 4 steps, then have a single function that calls down to all 4 in series.

**Comment by allenday** [comment]
@obsh please refactor ErrorCorrectionFn when this issue is resolved, thx.

@lachlancoin heads up

**Comment by lachlancoin** [comment]
This has been done.
