### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by xlinxlin** [mdcao/japsa#31]
Hi, I got the following error message during the installation process. The installation command I used is: `sudo make install INSTALL_DIR=~/.usr/local MXMEM=7000m SERVER=true JLP=false`
```
src/main/java/japsa/util/deploy/Deploy.java:55: error: cannot find symbol
import japsa.tools.bio.np.FlankSeqsDetectorCmd;
                         ^
  symbol:   class FlankSeqsDetectorCmd
  location: package japsa.tools.bio.np
src/main/java/japsa/util/deploy/Deploy.java:184: error: cannot find symbol
		tools.add(new FlankSeqsDetectorCmd());
		              ^
  symbol:   class FlankSeqsDetectorCmd
  location: class Deploy
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
Makefile:88: recipe for target 'target/main-classes/./japsa/bio/misc/alignCompress/AlignCompress.class' failed
make: *** [target/main-classes/./japsa/bio/misc/alignCompress/AlignCompress.class] Error 1

```

**Comment by xlinxlin** [comment]
I just noticed it in history that you may accidentally deleted `FlankSeqsDetectorCmd.java`. Can you check it? @hsnguyen 
![japsa](https://user-images.githubusercontent.com/28823126/63022764-df7d7a80-bea3-11e9-8f45-840d7c4ea265.jpg)

**Comment by xlinxlin** [comment]
I just sent a pull quest to fix this issue (at least it works for me), please check it. @mdcao @hsnguyen

**Comment by hsnguyen** [comment]
Thank you very much for such rapid feedback. I just tried to move FlankDetect module out of dev space and forgot to commit the actual file yesterday. 
I just fixed it. It's just exactly the same as your pull request but change the scriptName. 
Cheers,
