### ISSUE TITLE
Understanding of jsa.np.rtSpeciesTyping output

### ISSUE THREAD

**Issue by xlinxlin** [mdcao/japsa#34]
Hi,
We just tested `jsa.np.rtSpeciesTyping` tool with a sample data and produced a `.tsv` file. Can you help me to explain what is the meaning of the header (reads, bases, prob, err, tAligned, sAligned)? Thanks a lot!
![japsa](https://user-images.githubusercontent.com/28823126/67930834-e83b3e00-fbc0-11e9-8b8c-de2447d22cfe.png)

**Comment by hsnguyen** [comment]
`read` and `base` are the number of read and base counting till the time reported respectively.
`tAligned` and `sAligned` are the number of reads aligned totally and for that individual species.
`prob` and `error` present the mean and error of the  95% confident interval for a multinomial proportion of each species, modelled based on the read count.
So basically, `prob` will give you an approx. proportion of a species found in the mixture.

**Comment by xlinxlin** [comment]
@hsnguyen Thanks!
